# Workflow setup for building Native iOS project
workflows:
    ios-project: # workflow ID
        name: iOS project # workflow name
        environment:
            xcode: latest
            cocoapods: default
        scripts:
             - name: Install CocoaPods dependencies
               script: | 
                    pod install
             - name: build your app without sigining 
               script: | 
                     xcodebuild build -workspace "swiftly.xcworkspace" -scheme "swiftly" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        publishing:
          email:
            recipients:
              - ibrarjee.343@gmail.com 
